export const movies = [
    {
        id: 1,
        title: '기생충',
        director: '봉준호',
        actors: '송강호, 이선균, 조여정',
        poster: 'https://upload.wikimedia.org/wikipedia/en/5/53/Parasite_%282019_film%29.png',
        runningTime: 131,
        plot: '전원백수로 살 길 막막하지만 사이는 좋은 기택(송강호) 가족. 장남 기우(최우식)에게 명문대생 친구가 연결시켜 준 고액 과외 자리는 모처럼 싹튼 고정수입의 희망이다. 온 가족의 도움과 기대 속에 박사장(이선균) 집으로 향하는 기우. 글로벌 IT기업 CEO인 박사장의 저택에 도착하자 젊고 아름다운 사모님 연교(조여정)가 기우를 맞이한다. 그러나 이렇게 시작된 두 가족의 만남 뒤로, 걷잡을 수 없는 사건이 기다리고 있었으니…',
        distributor: 'CJ ENM',
        class: '15세 이상 관람가',
        releaseDate: '2019.05.30',
        reservation_rate:17.5,
        genre:'드라마'
    },
    {
        id: 2,
        title: '기생충',
        director: '봉준호',
        actors: '송강호, 이선균, 조여정',
        poster: 'https://upload.wikimedia.org/wikipedia/en/5/53/Parasite_%282019_film%29.png',
        runningTime: 131,
        plot: '전원백수로 살 길 막막하지만 사이는 좋은 기택(송강호) 가족. 장남 기우(최우식)에게 명문대생 친구가 연결시켜 준 고액 과외 자리는 모처럼 싹튼 고정수입의 희망이다. 온 가족의 도움과 기대 속에 박사장(이선균) 집으로 향하는 기우. 글로벌 IT기업 CEO인 박사장의 저택에 도착하자 젊고 아름다운 사모님 연교(조여정)가 기우를 맞이한다. 그러나 이렇게 시작된 두 가족의 만남 뒤로, 걷잡을 수 없는 사건이 기다리고 있었으니…',
        distributor: 'CJ ENM',
        class: '15세 이상 관람가',
        releaseDate: '2019.05.30',
        reservation_rate:17.5
    },
    {
        id: 3,
        title: '기생충',
        director: '봉준호',
        actors: '송강호, 이선균, 조여정',
        poster: 'https://upload.wikimedia.org/wikipedia/en/5/53/Parasite_%282019_film%29.png',
        runningTime: 131,
        plot: '전원백수로 살 길 막막하지만 사이는 좋은 기택(송강호) 가족. 장남 기우(최우식)에게 명문대생 친구가 연결시켜 준 고액 과외 자리는 모처럼 싹튼 고정수입의 희망이다. 온 가족의 도움과 기대 속에 박사장(이선균) 집으로 향하는 기우. 글로벌 IT기업 CEO인 박사장의 저택에 도착하자 젊고 아름다운 사모님 연교(조여정)가 기우를 맞이한다. 그러나 이렇게 시작된 두 가족의 만남 뒤로, 걷잡을 수 없는 사건이 기다리고 있었으니…',
        distributor: 'CJ ENM',
        class: '15세 이상 관람가',
        releaseDate: '2019.05.30',
        reservation_rate:17.5
    },
    {
        id: 4,
        title: '올드보이',
        director: '박찬욱',
        actors: '최민식, 유지태',
        poster: 'https://upload.wikimedia.org/wikipedia/en/6/67/Oldboykoreanposter.jpg',
        reservation_rate:14.6,
    },
    {
        id: 5,
        title: '올드보이',
        director: '박찬욱',
        actors: '최민식, 유지태',
        poster: 'https://upload.wikimedia.org/wikipedia/en/6/67/Oldboykoreanposter.jpg',
        reservation_rate:14.6,
    },
    {
        id: 6,
        title: '올드보이',
        director: '박찬욱',
        actors: '최민식, 유지태',
        poster: 'https://upload.wikimedia.org/wikipedia/en/6/67/Oldboykoreanposter.jpg',
        reservation_rate:14.6,
    },
];